brian-team/brian2genn

brian2genn/device.py
This was introduced in brian2 with brian-team/brian2#750. For now, the code is only copy&pasted from there but hopefully with a future refactoring this redundancy should no longer be necessary (see source code comments).
=> Check for "unstable integration"

brian2genn/device.py, brian2genn/templates/model.cpp
This fixes #28 by raising a `NotImplementedError` when an `on_pre` statement refers to a pre-synaptic variable or an `on_post` statement refers to a post-synaptic variable. This is actually more restrictive than necessary, since *reading* such a variable should be fine, but checking for that would be more complicated. What do you think, is this important for a first version of `brian2genn`? There are certainly models where the synaptic effect depends on some pre-synaptic variable, but for those we'd also need to figure out how to deal with the different semantics between Brian and GeNN related to delays (Brian would use the value at the time of the synaptic action, GeNN at the time of the pre-synaptic spike).
This PR also refactors a bit of code to remove redundancies and is built on top …
=> Check which variables on_pre and on_post statements refer to

README.md, brian2genn/correctness_testing.py, brian2genn/device.py, brian2genn/preferences.py, brian2genn/templates/GNUmakefile, brian2genn/templates/WINmakefile, brian2genn/templates/model.cpp, docs_sphinx/introduction/preferences.rst
Not sure if you agree, but I think it might be simpler if Brian2GeNN just uses Brian's compiler optimization flags instead of GeNN-specific ones. Or do you think users will often set optimization flags differently for the two?
=> Use Brian's general compiler preferences

brian2genn/device.py
Brian2GeNN does not correctly deal with scalar variables, but it would happily take them and treat them as array variables. Now it raises a `NotImplementedError` instead.
=> Do not allow scalar variables (not correctly supported)

.travis.yml, appveyor.yml, setup.py
This updates our test environment, so it tests both against a "stable version" (latest release of Brian 2 and GeNN master), as well as against a "development version" (latest version from Brian 2 master and GeNN development branch). Failures against the second do not mark the full test as failures, but it will give us a useful indication that we broke something.
=> Test latest dependencies

brian2genn/device.py, brian2genn/templates/neuron_code.cpp, brian2genn/templates/template_notes.txt
This PR fixes #41 and the issue mentioned here: https://github.com/brian-team/brian2genn/issues/43#issuecomment-280394751.
Instead of creating individual `CodeObject`s for a `NeuronGroup`'s stateupdate, threshold, and reset, we first store their information into `DelayedCodeObject`s (which do nothing except to store the code, variables, etc.) and then later merge them all into one code object, after adding the abstract code for the threshold to the end of the stateupdate code.
This fixes:
1. Subexpressions can be used in threshold conditions (#41), since now multiple-line conditions will be calculated after the state update and stored into a boolean variable `_cond`; the actual threshold condition is then just `_cond`.
2. Since stateupdate, threshold, and reset now share a single …
=> [MRG] Fix issues around threshold/resets and subexpressions and support functions

.travis.yml, brian2genn/device.py, brian2genn/templates/main.cpp
I noticed that two new Brian 2 tests were failing with Brian2GeNN for two reasons:
* Refractoriness information (`lastspike` and `not_refractory`) where only updated when the reset statement was not empty
* Seeds where only initialized for neurons, not for synapses (i.e. if a synaptic statement used a random number, this would be based on uninitialized memory, most likely giving many duplicate random numbers)
This PR fixes these two issues (let's wait whether the tests all run through, though).
=> [MRG] Bug fixes

brian2genn/b2glib/convert_synapses.h, brian2genn/device.py
As stated in #10, Brian2GeNN does not correctly handle multiple connections between a pair of neurons (which is a limitation of GeNN itself, I think?). There's no very clean solution to handle this case, since we don't now whether there are any multisynapses until we have generated them all. The approach in this PR is to check during the conversion of "Brian synapses" to "GeNN synapses". To give a useful error message on the Python level, the code will not only print out an error message but will also exit with a custom error level that is then processed on the Python side and raises a `NotImplementedError`.
Not sure whether you are happy with my check for multiple synapses, though. Performance-wise it should not have a noticeable effect, I think.
=> Check for multiple synapses

brian2genn/device.py, brian2genn/genn_generator.py, brian2genn/templates/GNUmakefile, brian2genn/templates/WINmakefile, brian2genn/templates/engine.cpp, brian2genn/templates/neuron_code.cpp, brian2genn/templates/run_regularly_scalar_code.cpp
This PR implements a simple way to add support for `PoissonInput`, `(constant over dt)` subexpressions, and `run_regularly` operations. The basic approach is very simple: the respective update code is added to the neuron code, before the usual state update code. This means that there are of course several limits to the support (e.g. it only supports neurons, but not synapses, you cannot reschedule the code to a different slot, etc.), but it is certainly better than nothing. For `run_regularly`, it allows a dt that is a multiple of the standard dt -- it wouldn't make much sense to use a `run_regularly` operation with the same dt as the group. Unfortunately one major use case is not supported: `run_regularly` can not update a scalar/shared variable (such as a presented stimulus) -- I don't …
=> [MRG] Add support for PoissonInput, constant over dt, and run_regularly

.travis.yml, appveyor.yml, brian2genn/device.py, brian2genn/preferences.py
To make installation easier for users that did not use GeNN before, this PR removes the need for the user to set `PATH` manually. Brian2GeNN will now use `$GENN_PATH/lib/bin` to call `genn-buildmodel.sh` directly. Also, since setting environmental variables might not be obvious to all users in the first place (and is different depending on the way you launch scripts), this PR adds an option to set a preference for the path instead.
=> [MRG] Simplify setup to use GeNN

brian2genn/device.py
And here's another one: as noted in #49, we still allowed setting synaptic delays with string expressions which resulted in heterogeneous delays, not supported by Brian2GeNN. This PR adds checks to raise errors when you try to do that, so hopefully now there shouldn't be any possibility left to set heterogeneous delays without getting a clear error message.
=> [MRG] Raise an error when trying to set delays with string expressions

.travis.yml, appveyor.yml, brian2genn/genn_generator.py
Embarrassingly, I only now realized that the introduction of the `timestep` function (for deterministic refractory times: brian-team/brian2#962, brian-team/brian2#949) that we introduced with Brian 2.1.3 breaks `Brian2GeNN`... This PR should fix it by adding a CUDA-compatible implementation of `timestep`. The compatibility trick for `isinf` is copied from the Brian 2 implementation, it seems to be necessary on Windows with older versions of MSVC.
=> [MRG] Add a `timestep` implementation make it work with Brian 2.1.3

brian2genn/genn_generator.py
Small bug fix on the new _timestep function. It's annoying but one needs to use ```std::isinf``` on the host side but plainly ```isinf``` on the device side.
=> Bug in _timestep function related to different host and device ```isinf```

.travis.yml, appveyor.yml, brian2genn/b2glib/convert_synapses.h, brian2genn/genn_generator.py, brian2genn/templates/main.cpp
To be consistent with Brian2's semantics for division etc. (and to not fail the new tests), we have to apply the same changes for `_brian_mod`, `_brian_floordiv` and `_timestep`.
=> [MRG] Apply Brian2's latest changes related to division/mod and timestep

.travis.yml, appveyor.yml, brian2genn/device.py, brian2genn/templates/main.cpp
This adds code slots that can be used with `device.insert_code`. This is basically the same as the change introduced for Brian2 standalone with PR brian-team/brian2#1006 but with additional `before_run` and `after_run` slots. Those are needed because in Brian2GeNN, the actual simulation run is not part of the "main lines".
=> [MRG] Add code slots for the `device.insert_code` mechanism

.travis.yml, appveyor.yml, brian2genn/device.py, brian2genn/preferences.py, brian2genn/templates/model.cpp
I did this to run a benchmark with fixed block sizes controlled from the brian2genn script, overriding the usual GeNN blocksize optimization. 
This exposes preferences for optimising blocksize or not and the individual blocksizes for all GeNN CUDA kernels. 
Users can now set ```devices.genn.optimise_blocksize= False``` and any blocksize, e.g. ```devices.genn.neuron_blocksize= 128``` to control block sizes individually.
I think it does not hurt to make this available to everybody in the next release.
=> I exposed the blocksize related preferences in GeNN to Brian2Genn users.

brian2genn/codeobject.py, brian2genn/templates/model.cpp, continuous-integration/azure-steps.yml
Brian2GeNN has been using the GeNN 2.X syntax for defining models. This has continued to be supported via wrappers in GeNN 3.X, but all newer GeNN features (e.g. #57) and we plan on deprecating this syntax entirely in the next major release. 
This PR updates the model.cpp template to use the new syntax.
=> Use new GeNN syntax in model

brian2genn/codeobject.py, brian2genn/genn_generator.py, brian2genn/templates/engine.cpp, brian2genn/templates/main.cpp, brian2genn/templates/neuron_code.cpp, brian2genn/templates/spikegenerator.cpp, setup.py
I only now realized that changes in Brian 2 that were published with the latest release unfortunately completely break the functionality of `SpikeGeneratorGroup` in Brian2GeNN. The reason is that we greatly improved the handling of periods in `SpikeGeneratorGroup`, which entailed a different default value for the period: before, we use a very large value (as a proxy for "infinite"), now we use 0. Brian2GeNN still used the old algorithm which unfortunately does not handle a period of 0 well at all. I fix this in this PR, and also slightly changed the way the time is advanced during a run which became necessary with the changes because `SpikeGeneratorGroup` now makes use of the integer timestep `iT`.
Unfortunately I also discovered one more thing, apparently I did not run the full test …
=> [WIP] Fix SpikeGeneratorGroup and other incompatibilities

azure-pipelines.yml, brian2genn/device.py, brian2genn/genn_generator.py, brian2genn/insyn.py, continuous-integration/azure-steps.yml, examples/testSummedVars.py
This pull request is adding the feature of summed variables to Brian2Genn. In the wake of allowing summed variables, I also had to lift the restriction that every synapse has to have a post-synaptic effect (in the narrow sense of having a "post_write_var") as the post-synaptic effect could well come through a summed variable. I suspect that the use case in teili by @schlowm0 might re-invent what GeNN post-synapses do but for the moment I think this pull request removes a roadblock for using brian2genn from teili.
=> Summed variables

brian2genn/device.py, brian2genn/templates/engine.cpp, brian2genn/templates/main.cpp, brian2genn/templates/neuron_code.cpp, brian2genn/templates/run_regularly_scalar_code.cpp, docs_sphinx/introduction/exclusions.rst
This PR still needs a bit more thorough testing, but it seems to work in principle. `run_regularly` operations are now always executed on the CPU, which comes with a number of advantages over the previous solution:
* Functions that are only available on the CPU can be used (most importantly, `TimedArray` #13).
* `Synapses` can have `run_regularly` operations as well (Fixes #58)
* More than one `run_regulary` operation per object allowed (not sure how relevant this is in practice, though).
If the user has a `run_regularly` operation that gets executed every time step, then the new approach will probably slow the simulation down a bit. For the more standard use case of a rarely executed operation, I don't think we'll see any difference.
Fixes #96.
=> [MRG] run_regularly operations on the CPU

brian2genn/device.py
Using synapses with current Brian 2 master failed with a `NotImplementedError` related to Brian's spike queue (which we are not using in Brian2GeNN). Unfortunately, all errors of this kind lead to tests being marked as "skipped" instead of "failed", so I didn't notice it in the test runs earlier. This PR should fix this issue. It also raises a `TypeError` instead of a `NotImplementedError` in the previously failing situation, so similar errors shouldn't go unnoticed in the future.
=> [MRG] Compatibility fixes

brian2genn/device.py, brian2genn/templates/main.cpp
GeNN 4 made the timing system slightly simpler to interact with but also renamed things. If kernel timing is enabled, the time file will contain 'neuronUpdateTime', 'presynapticUpdateTime', 'postsynapticUpdateTime', 'synapseDynamicsTime', 'initTime', 'initSparseTime'
=> Support for GeNN 4 timing

brian2genn/device.py, brian2genn/templates/max_row_length_array.cpp, brian2genn/templates/max_row_length_generator.cpp, brian2genn/templates/model.cpp, examples/simple_example_with_synapses.py
In this pull request I constructed a different way of solving the multiple connect calls issue. It is now doing all the max_row_length and max_col_length work in C++. For the connections created from arrays, a max_row_length_XXX_arrays code_object is run that apes the normal synapse creation from files. I also moved the actual max operation on all incoming and outgoing synapses numbers into the model.cpp template, which means it is only done once, not for every code object (connect call) repeatedly. To be honest, this is probably the cleaner solution and as we are already loading arrays anyway, it is probably as performant as the other, incomplete solution. I probably prefer it over #107 ...
=> Fix multiple connect v2

brian2genn/device.py, examples/simple_example_with_synapses.py
Ok ... here is a suggestion of how to fix the problem with multiple connect calls that lead to "array" type connections. This follows strategy 1 of doing it in Python.
However, it still does not work when connections are generated with connect calls where one call leads to an array on disk and another to a generator code_object.
In my mind there are two possibilities:
1. change tack and indeed load arrays in the buildmodel phase and count synapses aping the full synapse creation cycle of the eventual simulation.
2. make an upper bound by assuming all source (target) neurons have the max connections from the file based connectivity and add the connections from the created connectivity; this will overestimate the the max_row_length (max_col_length) but maybe that is acceptable?
=> Solution for multiple connect calls that lead to arrays 

docs_sphinx/introduction/index.rst
Fixes a naming mistake in the documentation.
`set_device('genn', useGPU=False, debug=True)`
should be
`set_device('genn', use_GPU=False, debug=True)`
as that is the name in the run function of the GeNN device:
https://github.com/brian-team/brian2genn/blob/4da63141e9f4a6e4785349498e61e61e0ddae589/brian2genn/device.py#L1019
When using the wrong `useGPU` I get the following error message:
```
File "...../python3.8/site-packages/brian2/devices/cpp_standalone/device.py", line 1514, in network_run
self.build(direct_call=False, **self.build_options)
TypeError: build() got an unexpected keyword argument 'useGPU'
```
It works with `use_GPU`.
=> Docs: Fix parameter name of `set_device('genn')`

brian2genn/device.py, brian2genn/templates/model.cpp
Fix for issue #131. I only included headers defined via `prefs.codegen.cpp.headers`.
=> Include custom headers in `model.cpp`

brian2genn/device.py
The root cause for the problem was that for situations where sub-populations of neuron populations were connected
and a state monitor for the synapses instantiated, the pre-template prep code would identify the size of the connected sub-populations for the ```srcN``` and ```trgN``` variables of the ```stateMonitorModel```. These variables are then used for the argument list of the ```convert_dense_matrix_2_dynamic_arrays``` and ```convert_sparse_synapses_2_dynamic_arrays``` calls that translate GeNN synaptic data into brian format synaptic data. Because brian2genn implements sub-populations only by connectivity matrices between full populations, the conversion functions need the size of the full populations, not of the connected sub-populations.
I believe the ```srcN``` and ```trgN``` …
=> This is a fix for issue #136. 

brian2genn/device.py, brian2genn/templates/engine.cpp
Fixes #139.
In order to maintain my sanity in the template code, I've also cleaned up indentation in templates/engine.cpp prior to implementing slow clock support.
I couldn't see any tests for slow clocks, but I've tested the feature to my satisfaction informally and confirmed locally that there are no regressions (at least as covered by unit tests).
=> Support slow statemonitor clocks

brian2genn/device.py, brian2genn/templates/main.cpp
This is how the slot is called in brian2 now, see PR brian-team/brian2#1390
Might need changes in the brian2genn_benchmarks repository if those should be run again.
=> Rename `insert_code` slots `run` to `network_run`

brian2genn/device.py
Apparently the `cuda_path` pref was moved at some point, but the error message related to it wasn't updated. This PR fixes this.
=> Correctly identify cuda_path prefs location
